source.. = src/main/java/,\
           src/main/resources/,\
           target/generated-sources/annotations/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               lib/
