source.. = src/main/java/,\
           src/main/resources/,\
           .apt_generated/,\
           target/generated-sources/annotations/
output.. = target/classes/
bin.includes = META-INF/,\
               OSGI-INF/,\
               .,\
               plugin.xml,\
               lib/